export const categories = [
  {
    id: 1,
    name: "Technology & IT",
    subcategories: [
      {
        id: "1",
        name: "Web Development",
        providers: [
          {
            id: 1,
            firstName: "John",
            lastName: "Doe",
            skills: "HTML, CSS, JavaScript",
            needs: "Graphic Design",
            email: "john@example.com",
            phone: "123-456-7890",
          },
          {
            id: 2,
            firstName: "Alice",
            lastName: "Smith",
            skills: "React, Node.js",
            needs: "Backend Development",
            email: "alice@example.com",
            phone: "987-654-3210",
          },
        ],
      },
      {
        id: "2",
        name: "Graphic Design",
        providers: [
          {
            id: 3,
            firstName: "Mike",
            lastName: "Johnson",
            skills: "Adobe Illustrator, Photoshop",
            needs: "Web Development",
            email: "mike@example.com",
            phone: "555-123-4567",
          },
          {
            id: 4,
            firstName: "Emily",
            lastName: "Brown",
            skills: "Logo Design, Branding",
            needs: "",
            email: "emily@example.com",
            phone: "222-333-4444",
          },
        ],
      },
      {
        id: "3",
        name: "Coding Assistance",
        providers: [
          {
            id: 5,
            firstName: "Chris",
            lastName: "Miller",
            skills: "Python, Java",
            needs: "Code Review",
            email: "chris@example.com",
            phone: "777-888-9999",
          },
          {
            id: 6,
            firstName: "Eva",
            lastName: "White",
            skills: "JavaScript, TypeScript",
            needs: "Frontend Development",
            email: "eva@example.com",
            phone: "111-222-3333",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Home Services",
    subcategories: [
      {
        id: "4",
        name: "Plumbing",
        providers: [
          {
            id: 7,
            firstName: "Lily",
            lastName: "Clark",
            skills: "Pipe Repair, Installation",
            needs: "Electrical",
            email: "lily@example.com",
            phone: "444-555-6666",
          },
          {
            id: 8,
            firstName: "Carlos",
            lastName: "Garcia",
            skills: "Leak Detection, Plumbing Maintenance",
            needs: "Cleaning",
            email: "carlos@example.com",
            phone: "999-000-1111",
          },
        ],
      },
      {
        id: "5",
        name: "Electrical",
        providers: [
          {
            id: 9,
            firstName: "Sophie",
            lastName: "Leblanc",
            skills: "Wiring, Troubleshooting",
            needs: "Plumbing",
            email: "sophie@example.com",
            phone: "666-777-8888",
          },
          {
            id: 10,
            firstName: "Alex",
            lastName: "Johnson",
            skills: "Electrical Panel Upgrades, Lighting",
            needs: "Cleaning",
            email: "alex@example.com",
            phone: "123-987-4567",
          },
        ],
      },
      {
        id: "6",
        name: "Cleaning",
        providers: [
          {
            id: 11,
            firstName: "Mia",
            lastName: "Smith",
            skills: "House Cleaning",
            needs: "",
            email: "mia@example.com",
            phone: "987-123-6543",
          },
          {
            id: 12,
            firstName: "Ryan",
            lastName: "Miller",
            skills: "Carpet Cleaning, Deep Cleaning",
            needs: "",
            email: "ryan@example.com",
            phone: "111-222-3333",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "Language Exchange",
    subcategories: [
      {
        id: "7",
        name: "English",
        providers: [
          {
            id: 13,
            firstName: "David",
            lastName: "Brown",
            skills: "English",
            needs: "Spanish",
            email: "david@example.com",
            phone: "333-444-5555",
          },
          {
            id: 14,
            firstName: "Emma",
            lastName: "Jones",
            skills: "English Conversation",
            needs: "French",
            email: "emma@example.com",
            phone: "666-777-8888",
          },
        ],
      },
      {
        id: "8",
        name: "Spanish",
        providers: [
          {
            id: 15,
            firstName: "Olivia",
            lastName: "Wilson",
            skills: "Spanish",
            needs: "English",
            email: "olivia@example.com",
            phone: "999-111-2222",
          },
          {
            id: 16,
            firstName: "Lucas",
            lastName: "Martinez",
            skills: "Conversational Spanish",
            needs: "English",
            email: "lucas@example.com",
            phone: "333-222-1111",
          },
        ],
      },
      {
        id: "9",
        name: "French",
        providers: [
          {
            id: 17,
            firstName: "Sophie",
            lastName: "Leblanc",
            skills: "French",
            needs: "English",
            email: "sophie@example.com",
            phone: "666-777-8888",
          },
          {
            id: 18,
            firstName: "Pierre",
            lastName: "Dubois",
            skills: "Conversational French",
            needs: "English",
            email: "pierre@example.com",
            phone: "444-555-6666",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "Health & Wellness",
    subcategories: [
      {
        id: "10",
        name: "Fitness Training",
        providers: [
          {
            id: 19,
            firstName: "Victoria",
            lastName: "Fath",
            skills: "Personal Training, Yoga",
            needs: "Nutrition Consultation",
            email: "zoe@example.com",
            phone: "111-222-3333",
          },
          {
            id: 20,
            firstName: "Jake",
            lastName: "Anderson",
            skills: "Cardio Workouts, Strength Training",
            needs: "Mental Health Support",
            email: "jake@example.com",
            phone: "777-888-9999",
          },
        ],
      },
      {
        id: "11",
        name: "Nutrition Consultation",
        providers: [
          {
            id: 21,
            firstName: "Mia",
            lastName: "Smith",
            skills: "Dietitian",
            needs: "Fitness Training",
            email: "mia@example.com",
            phone: "987-123-6543",
          },
          {
            id: 22,
            firstName: "Ethan",
            lastName: "Brown",
            skills: "Meal Planning",
            needs: "Mental Health Support",
            email: "ethan@example.com",
            phone: "555-666-7777",
          },
        ],
      },
      {
        id: "12",
        name: "Mental Health Support",
        providers: [
          {
            id: 23,
            firstName: "Olivia",
            lastName: "Miller",
            skills: "Counseling",
            needs: "Fitness Training",
            email: "olivia@example.com",
            phone: "999-000-1111",
          },
          {
            id: 24,
            firstName: "Lucas",
            lastName: "Jones",
            skills: "Mindfulness Meditation",
            needs: "",
            email: "lucas@example.com",
            phone: "222-333-4444",
          },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Creative Arts",
    subcategories: [
      {
        id: "13",
        name: "Music Lessons",
        providers: [
          {
            id: 25,
            firstName: "Ava",
            lastName: "Smith",
            skills: "Piano, Violin",
            needs: "Art Classes",
            email: "ava@example.com",
            phone: "777-888-9999",
          },
          {
            id: 26,
            firstName: "Jack",
            lastName: "Wilson",
            skills: "Guitar, Drums",
            needs: "",
            email: "jack@example.com",
            phone: "111-222-3333",
          },
        ],
      },
      {
        id: "14",
        name: "Art Classes",
        providers: [
          {
            id: 27,
            firstName: "Sophie",
            lastName: "Anderson",
            skills: "Painting, Drawing",
            needs: "Photography Services",
            email: "sophie@example.com",
            phone: "444-555-6666",
          },
          {
            id: 28,
            firstName: "Mia",
            lastName: "Jones",
            skills: "Sculpture, Mixed Media",
            needs: "",
            email: "mia@example.com",
            phone: "666-777-8888",
          },
        ],
      },
      {
        id: "15",
        name: "Photography Services",
        providers: [
          {
            id: 29,
            firstName: "Ethan",
            lastName: "Brown",
            skills: "Portrait Photography",
            needs: "Art Classes",
            email: "ethan@example.com",
            phone: "555-666-7777",
          },
          {
            id: 30,
            firstName: "Olivia",
            lastName: "Miller",
            skills: "Event Photography",
            needs: "",
            email: "olivia@example.com",
            phone: "999-000-1111",
          },
        ],
      },
    ],
  },
];
