export const serviceProviders = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    skills: "HTML, CSS, JavaScript",
    needs: "UI/UX Design",
    email: "john@example.com",
    phone: "123-456-7890",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    skills: "React, Node.js, MongoDB",
    needs: "API Integration",
    email: "jane@example.com",
    phone: "987-654-3210",
  },
  {
    id: 3,
    firstName: "Mike",
    lastName: "Johnson",
    skills: "Angular, TypeScript, Firebase",
    needs: "Performance Optimization",
    email: "mike@example.com",
    phone: "555-123-4567",
  },
  {
    id: 4,
    firstName: "Sarah",
    lastName: "Williams",
    skills: "Vue.js, SASS, GraphQL",
    needs: "Responsive Design",
    email: "sarah@example.com",
    phone: "222-333-4444",
  },
  {
    id: 5,
    firstName: "David",
    lastName: "Brown",
    skills: "Python, Django, PostgreSQL",
    needs: "Database Architecture",
    email: "david@example.com",
    phone: "666-999-7777",
  },
];
